// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace DMS.Web.Host.Controllers
{
    public partial class ProjectsController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ProjectsController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddAlternative()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddAlternative);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddFactor()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddFactor);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Details()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Details);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Edit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Delete()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Delete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteConfirmed()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteConfirmed);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult OrnessTest()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.OrnessTest);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult QuantifierTest()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QuantifierTest);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GenerateWeights()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GenerateWeights);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DoAggregation()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DoAggregation);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AggregationDetails()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AggregationDetails);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult StartPsychometricQuestionnaire()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.StartPsychometricQuestionnaire);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PsychometricQuestionnaireQuestion()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PsychometricQuestionnaireQuestion);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult FillRatings()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FillRatings);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult FillPossibilities()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FillPossibilities);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult FillProbabilities()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FillProbabilities);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult InputLambda()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InputLambda);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ProjectsController Actions { get { return MVC.Projects; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Projects";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Projects";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Add = "Add";
            public readonly string Action = "Action";
            public readonly string AddAlternative = "AddAlternative";
            public readonly string AddFactor = "AddFactor";
            public readonly string Details = "Details";
            public readonly string Edit = "Edit";
            public readonly string Delete = "Delete";
            public readonly string DeleteConfirmed = "Delete";
            public readonly string OrnessTest = "OrnessTest";
            public readonly string QuantifierTest = "QuantifierTest";
            public readonly string GenerateWeights = "GenerateWeights";
            public readonly string DoAggregation = "DoAggregation";
            public readonly string AggregationDetails = "AggregationDetails";
            public readonly string StartPsychometricQuestionnaire = "StartPsychometricQuestionnaire";
            public readonly string PsychometricQuestionnaireQuestion = "PsychometricQuestionnaireQuestion";
            public readonly string FillRatings = "FillRatings";
            public readonly string FillPossibilities = "FillPossibilities";
            public readonly string FillProbabilities = "FillProbabilities";
            public readonly string InputLambda = "InputLambda";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Add = "Add";
            public const string Action = "Action";
            public const string AddAlternative = "AddAlternative";
            public const string AddFactor = "AddFactor";
            public const string Details = "Details";
            public const string Edit = "Edit";
            public const string Delete = "Delete";
            public const string DeleteConfirmed = "Delete";
            public const string OrnessTest = "OrnessTest";
            public const string QuantifierTest = "QuantifierTest";
            public const string GenerateWeights = "GenerateWeights";
            public const string DoAggregation = "DoAggregation";
            public const string AggregationDetails = "AggregationDetails";
            public const string StartPsychometricQuestionnaire = "StartPsychometricQuestionnaire";
            public const string PsychometricQuestionnaireQuestion = "PsychometricQuestionnaireQuestion";
            public const string FillRatings = "FillRatings";
            public const string FillPossibilities = "FillPossibilities";
            public const string FillProbabilities = "FillProbabilities";
            public const string InputLambda = "InputLambda";
        }


        static readonly ActionParamsClass_Add s_params_Add = new ActionParamsClass_Add();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Add AddParams { get { return s_params_Add; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Add
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_AddAlternative s_params_AddAlternative = new ActionParamsClass_AddAlternative();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddAlternative AddAlternativeParams { get { return s_params_AddAlternative; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddAlternative
        {
            public readonly string index = "index";
        }
        static readonly ActionParamsClass_AddFactor s_params_AddFactor = new ActionParamsClass_AddFactor();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddFactor AddFactorParams { get { return s_params_AddFactor; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddFactor
        {
            public readonly string index = "index";
        }
        static readonly ActionParamsClass_Details s_params_Details = new ActionParamsClass_Details();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Details DetailsParams { get { return s_params_Details; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Details
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Edit s_params_Edit = new ActionParamsClass_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Edit EditParams { get { return s_params_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Edit
        {
            public readonly string id = "id";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_Delete s_params_Delete = new ActionParamsClass_Delete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Delete DeleteParams { get { return s_params_Delete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Delete
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DeleteConfirmed s_params_DeleteConfirmed = new ActionParamsClass_DeleteConfirmed();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteConfirmed DeleteConfirmedParams { get { return s_params_DeleteConfirmed; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteConfirmed
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_OrnessTest s_params_OrnessTest = new ActionParamsClass_OrnessTest();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_OrnessTest OrnessTestParams { get { return s_params_OrnessTest; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_OrnessTest
        {
            public readonly string a = "a";
            public readonly string n = "n";
        }
        static readonly ActionParamsClass_QuantifierTest s_params_QuantifierTest = new ActionParamsClass_QuantifierTest();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_QuantifierTest QuantifierTestParams { get { return s_params_QuantifierTest; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_QuantifierTest
        {
            public readonly string a = "a";
            public readonly string n = "n";
        }
        static readonly ActionParamsClass_GenerateWeights s_params_GenerateWeights = new ActionParamsClass_GenerateWeights();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GenerateWeights GenerateWeightsParams { get { return s_params_GenerateWeights; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GenerateWeights
        {
            public readonly string id = "id";
            public readonly string method = "method";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_DoAggregation s_params_DoAggregation = new ActionParamsClass_DoAggregation();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DoAggregation DoAggregationParams { get { return s_params_DoAggregation; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DoAggregation
        {
            public readonly string id = "id";
            public readonly string aggregationType = "aggregationType";
            public readonly string lambda = "lambda";
        }
        static readonly ActionParamsClass_AggregationDetails s_params_AggregationDetails = new ActionParamsClass_AggregationDetails();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AggregationDetails AggregationDetailsParams { get { return s_params_AggregationDetails; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AggregationDetails
        {
            public readonly string id = "id";
            public readonly string aggregationId = "aggregationId";
        }
        static readonly ActionParamsClass_StartPsychometricQuestionnaire s_params_StartPsychometricQuestionnaire = new ActionParamsClass_StartPsychometricQuestionnaire();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_StartPsychometricQuestionnaire StartPsychometricQuestionnaireParams { get { return s_params_StartPsychometricQuestionnaire; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_StartPsychometricQuestionnaire
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_PsychometricQuestionnaireQuestion s_params_PsychometricQuestionnaireQuestion = new ActionParamsClass_PsychometricQuestionnaireQuestion();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PsychometricQuestionnaireQuestion PsychometricQuestionnaireQuestionParams { get { return s_params_PsychometricQuestionnaireQuestion; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PsychometricQuestionnaireQuestion
        {
            public readonly string id = "id";
            public readonly string index = "index";
            public readonly string selectedAnswers = "selectedAnswers";
        }
        static readonly ActionParamsClass_FillRatings s_params_FillRatings = new ActionParamsClass_FillRatings();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_FillRatings FillRatingsParams { get { return s_params_FillRatings; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_FillRatings
        {
            public readonly string id = "id";
            public readonly string aggregationType = "aggregationType";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_FillPossibilities s_params_FillPossibilities = new ActionParamsClass_FillPossibilities();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_FillPossibilities FillPossibilitiesParams { get { return s_params_FillPossibilities; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_FillPossibilities
        {
            public readonly string id = "id";
            public readonly string aggregationType = "aggregationType";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_FillProbabilities s_params_FillProbabilities = new ActionParamsClass_FillProbabilities();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_FillProbabilities FillProbabilitiesParams { get { return s_params_FillProbabilities; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_FillProbabilities
        {
            public readonly string id = "id";
            public readonly string aggregationType = "aggregationType";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_InputLambda s_params_InputLambda = new ActionParamsClass_InputLambda();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_InputLambda InputLambdaParams { get { return s_params_InputLambda; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_InputLambda
        {
            public readonly string id = "id";
            public readonly string aggregationType = "aggregationType";
            public readonly string viewModel = "viewModel";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Add = "Add";
                public readonly string AggregationDetails = "AggregationDetails";
                public readonly string Delete = "Delete";
                public readonly string Details = "Details";
                public readonly string FillRatings = "FillRatings";
                public readonly string GenerateWeights = "GenerateWeights";
                public readonly string Index = "Index";
                public readonly string InputLambda = "InputLambda";
                public readonly string OrnessTest = "OrnessTest";
                public readonly string PsychometricQuestionnaireQuestion = "PsychometricQuestionnaireQuestion";
                public readonly string QuantifierTest = "QuantifierTest";
            }
            public readonly string Add = "~/Views/Projects/Add.cshtml";
            public readonly string AggregationDetails = "~/Views/Projects/AggregationDetails.cshtml";
            public readonly string Delete = "~/Views/Projects/Delete.cshtml";
            public readonly string Details = "~/Views/Projects/Details.cshtml";
            public readonly string FillRatings = "~/Views/Projects/FillRatings.cshtml";
            public readonly string GenerateWeights = "~/Views/Projects/GenerateWeights.cshtml";
            public readonly string Index = "~/Views/Projects/Index.cshtml";
            public readonly string InputLambda = "~/Views/Projects/InputLambda.cshtml";
            public readonly string OrnessTest = "~/Views/Projects/OrnessTest.cshtml";
            public readonly string PsychometricQuestionnaireQuestion = "~/Views/Projects/PsychometricQuestionnaireQuestion.cshtml";
            public readonly string QuantifierTest = "~/Views/Projects/QuantifierTest.cshtml";
            static readonly _DisplayTemplatesClass s_DisplayTemplates = new _DisplayTemplatesClass();
            public _DisplayTemplatesClass DisplayTemplates { get { return s_DisplayTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _DisplayTemplatesClass
            {
                public readonly string ProjectTableRowModel = "ProjectTableRowModel";
            }
            static readonly _EditorTemplatesClass s_EditorTemplates = new _EditorTemplatesClass();
            public _EditorTemplatesClass EditorTemplates { get { return s_EditorTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _EditorTemplatesClass
            {
                public readonly string AddProjectViewModel = "AddProjectViewModel";
                public readonly string AlternativeModel = "AlternativeModel";
                public readonly string FactorModel = "FactorModel";
                public readonly string GenerateWeightsRequestModel = "GenerateWeightsRequestModel";
                public readonly string InputLambdaViewModel = "InputLambdaViewModel";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ProjectsController : DMS.Web.Host.Controllers.ProjectsController
    {
        public T4MVC_ProjectsController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        partial void AddOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Add()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Add);
            AddOverride(callInfo);
            return callInfo;
        }

        partial void AddOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, DMS.Web.Host.Models.AddProjectViewModel viewModel);

        public override System.Web.Mvc.ActionResult Add(DMS.Web.Host.Models.AddProjectViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Add);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            AddOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void ActionOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Action()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Action);
            ActionOverride(callInfo);
            return callInfo;
        }

        partial void AddAlternativeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int index);

        public override System.Web.Mvc.ActionResult AddAlternative(int index)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddAlternative);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "index", index);
            AddAlternativeOverride(callInfo, index);
            return callInfo;
        }

        partial void AddFactorOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int index);

        public override System.Web.Mvc.ActionResult AddFactor(int index)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddFactor);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "index", index);
            AddFactorOverride(callInfo, index);
            return callInfo;
        }

        partial void DetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        public override System.Web.Mvc.ActionResult Details(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Details);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DetailsOverride(callInfo, id);
            return callInfo;
        }

        partial void EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        public override System.Web.Mvc.ActionResult Edit(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditOverride(callInfo, id);
            return callInfo;
        }

        partial void EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, DMS.Web.Host.Models.AddProjectViewModel viewModel);

        public override System.Web.Mvc.ActionResult Edit(int id, DMS.Web.Host.Models.AddProjectViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            EditOverride(callInfo, id, viewModel);
            return callInfo;
        }

        partial void DeleteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        public override System.Web.Mvc.ActionResult Delete(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Delete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteOverride(callInfo, id);
            return callInfo;
        }

        partial void DeleteConfirmedOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        public override System.Web.Mvc.ActionResult DeleteConfirmed(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteConfirmed);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteConfirmedOverride(callInfo, id);
            return callInfo;
        }

        partial void OrnessTestOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, float? a, int? n);

        public override System.Web.Mvc.ActionResult OrnessTest(float? a, int? n)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.OrnessTest);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "a", a);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "n", n);
            OrnessTestOverride(callInfo, a, n);
            return callInfo;
        }

        partial void QuantifierTestOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, float? a, int? n);

        public override System.Web.Mvc.ActionResult QuantifierTest(float? a, int? n)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QuantifierTest);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "a", a);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "n", n);
            QuantifierTestOverride(callInfo, a, n);
            return callInfo;
        }

        partial void GenerateWeightsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, DMS.Domain.WeightGenerationMethod method);

        public override System.Web.Mvc.ActionResult GenerateWeights(int id, DMS.Domain.WeightGenerationMethod method)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GenerateWeights);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "method", method);
            GenerateWeightsOverride(callInfo, id, method);
            return callInfo;
        }

        partial void GenerateWeightsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, DMS.Domain.WeightGenerationMethod method, DMS.Web.Host.Models.GenerateWeightsRequestModel viewModel);

        public override System.Web.Mvc.ActionResult GenerateWeights(int id, DMS.Domain.WeightGenerationMethod method, DMS.Web.Host.Models.GenerateWeightsRequestModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GenerateWeights);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "method", method);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            GenerateWeightsOverride(callInfo, id, method, viewModel);
            return callInfo;
        }

        partial void DoAggregationOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, DMS.Domain.AggregationType aggregationType, decimal? lambda);

        public override System.Web.Mvc.ActionResult DoAggregation(int id, DMS.Domain.AggregationType aggregationType, decimal? lambda)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DoAggregation);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "aggregationType", aggregationType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lambda", lambda);
            DoAggregationOverride(callInfo, id, aggregationType, lambda);
            return callInfo;
        }

        partial void AggregationDetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, int aggregationId);

        public override System.Web.Mvc.ActionResult AggregationDetails(int id, int aggregationId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AggregationDetails);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "aggregationId", aggregationId);
            AggregationDetailsOverride(callInfo, id, aggregationId);
            return callInfo;
        }

        partial void StartPsychometricQuestionnaireOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        public override System.Web.Mvc.ActionResult StartPsychometricQuestionnaire(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.StartPsychometricQuestionnaire);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            StartPsychometricQuestionnaireOverride(callInfo, id);
            return callInfo;
        }

        partial void PsychometricQuestionnaireQuestionOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, int index);

        public override System.Web.Mvc.ActionResult PsychometricQuestionnaireQuestion(int id, int index)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PsychometricQuestionnaireQuestion);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "index", index);
            PsychometricQuestionnaireQuestionOverride(callInfo, id, index);
            return callInfo;
        }

        partial void PsychometricQuestionnaireQuestionOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, int index, System.Collections.Generic.IEnumerable<int> selectedAnswers);

        public override System.Web.Mvc.ActionResult PsychometricQuestionnaireQuestion(int id, int index, System.Collections.Generic.IEnumerable<int> selectedAnswers)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PsychometricQuestionnaireQuestion);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "index", index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "selectedAnswers", selectedAnswers);
            PsychometricQuestionnaireQuestionOverride(callInfo, id, index, selectedAnswers);
            return callInfo;
        }

        partial void FillRatingsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, DMS.Domain.AggregationType aggregationType);

        public override System.Web.Mvc.ActionResult FillRatings(int id, DMS.Domain.AggregationType aggregationType)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FillRatings);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "aggregationType", aggregationType);
            FillRatingsOverride(callInfo, id, aggregationType);
            return callInfo;
        }

        partial void FillRatingsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, DMS.Domain.AggregationType aggregationType, DMS.Web.Host.Models.FillRatingsViewModel viewModel);

        public override System.Web.Mvc.ActionResult FillRatings(int id, DMS.Domain.AggregationType aggregationType, DMS.Web.Host.Models.FillRatingsViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FillRatings);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "aggregationType", aggregationType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            FillRatingsOverride(callInfo, id, aggregationType, viewModel);
            return callInfo;
        }

        partial void FillPossibilitiesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, DMS.Domain.AggregationType aggregationType);

        public override System.Web.Mvc.ActionResult FillPossibilities(int id, DMS.Domain.AggregationType aggregationType)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FillPossibilities);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "aggregationType", aggregationType);
            FillPossibilitiesOverride(callInfo, id, aggregationType);
            return callInfo;
        }

        partial void FillPossibilitiesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, DMS.Domain.AggregationType aggregationType, DMS.Web.Host.Models.FillRatingsViewModel viewModel);

        public override System.Web.Mvc.ActionResult FillPossibilities(int id, DMS.Domain.AggregationType aggregationType, DMS.Web.Host.Models.FillRatingsViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FillPossibilities);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "aggregationType", aggregationType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            FillPossibilitiesOverride(callInfo, id, aggregationType, viewModel);
            return callInfo;
        }

        partial void FillProbabilitiesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, DMS.Domain.AggregationType aggregationType);

        public override System.Web.Mvc.ActionResult FillProbabilities(int id, DMS.Domain.AggregationType aggregationType)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FillProbabilities);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "aggregationType", aggregationType);
            FillProbabilitiesOverride(callInfo, id, aggregationType);
            return callInfo;
        }

        partial void FillProbabilitiesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, DMS.Domain.AggregationType aggregationType, DMS.Web.Host.Models.FillRatingsViewModel viewModel);

        public override System.Web.Mvc.ActionResult FillProbabilities(int id, DMS.Domain.AggregationType aggregationType, DMS.Web.Host.Models.FillRatingsViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FillProbabilities);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "aggregationType", aggregationType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            FillProbabilitiesOverride(callInfo, id, aggregationType, viewModel);
            return callInfo;
        }

        partial void InputLambdaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, DMS.Domain.AggregationType aggregationType);

        public override System.Web.Mvc.ActionResult InputLambda(int id, DMS.Domain.AggregationType aggregationType)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InputLambda);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "aggregationType", aggregationType);
            InputLambdaOverride(callInfo, id, aggregationType);
            return callInfo;
        }

        partial void InputLambdaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, DMS.Domain.AggregationType aggregationType, DMS.Web.Host.Models.InputLambdaViewModel viewModel);

        public override System.Web.Mvc.ActionResult InputLambda(int id, DMS.Domain.AggregationType aggregationType, DMS.Web.Host.Models.InputLambdaViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InputLambda);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "aggregationType", aggregationType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            InputLambdaOverride(callInfo, id, aggregationType, viewModel);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
