//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Web.Host.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMS.Web.Host.Resources.ApplicationStrings", typeof(ApplicationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დამატება.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პროექტის დამატება.
        /// </summary>
        public static string AddProject {
            get {
                return ResourceManager.GetString("AddProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to აგრეგაცია.
        /// </summary>
        public static string AggregationGeneration {
            get {
                return ResourceManager.GetString("AggregationGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ალფა მიკუთვნების კოეფიციენტი {0:0.###}.
        /// </summary>
        public static string AlfaCoefficient {
            get {
                return ResourceManager.GetString("AlfaCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ალტერნატივები.
        /// </summary>
        public static string Alternatives {
            get {
                return ResourceManager.GetString("Alternatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შეფასებები.
        /// </summary>
        public static string Assessments {
            get {
                return ResourceManager.GetString("Assessments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ავტორიზაცია.
        /// </summary>
        public static string Authorize {
            get {
                return ResourceManager.GetString("Authorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გაუქმება.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to საბოლოო შეფასების გენერაციის შემდეგ ექსპერტების შეცვლა არ შეიძლება.
        /// </summary>
        public static string CannotEditExpertsOnGeneratedFinal {
            get {
                return ResourceManager.GetString("CannotEditExpertsOnGeneratedFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დადასტურება.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to წაშლა.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to რედაქტირება.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ექსპერტების შეფასებები.
        /// </summary>
        public static string ExpertAssessments {
            get {
                return ResourceManager.GetString("ExpertAssessments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ექსპერტები.
        /// </summary>
        public static string Experts {
            get {
                return ResourceManager.GetString("Experts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფაქტორები.
        /// </summary>
        public static string Factors {
            get {
                return ResourceManager.GetString("Factors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to საბოლოო შეფასება.
        /// </summary>
        public static string FinalAssessment {
            get {
                return ResourceManager.GetString("FinalAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ზოგადი ინფორმაცია.
        /// </summary>
        public static string GeneralInfo {
            get {
                return ResourceManager.GetString("GeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გენერაცია.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შეიყვანეთ λ.
        /// </summary>
        public static string InputLambda {
            get {
                return ResourceManager.GetString("InputLambda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გამოსვლა.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პირდაპირი შეფასება.
        /// </summary>
        public static string ManualAssessment {
            get {
                return ResourceManager.GetString("ManualAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DMS.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შემდეგი.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პაროლი.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პროექტი წარმატებით შეიქმნა.
        /// </summary>
        public static string ProjectAdded {
            get {
                return ResourceManager.GetString("ProjectAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პროექტი.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პროექტები.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to კითხვების რაოდენობა (M).
        /// </summary>
        public static string QuestionCount {
            get {
                return ResourceManager.GetString("QuestionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ალფები.
        /// </summary>
        public static string QuestionGenerationCollection {
            get {
                return ResourceManager.GetString("QuestionGenerationCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შენახვა.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ტესტური შეფასება.
        /// </summary>
        public static string TestAssessment {
            get {
                return ResourceManager.GetString("TestAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მომხმარებლის სახელი.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მომხმარებლები.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to წონების გენერაცია.
        /// </summary>
        public static string WeightGeneration {
            get {
                return ResourceManager.GetString("WeightGeneration", resourceCulture);
            }
        }
    }
}
