//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Web.Host.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewTitles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewTitles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMS.Web.Host.Resources.ViewTitles", typeof(ViewTitles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პროექტის დამატება.
        /// </summary>
        public static string AddProject {
            get {
                return ResourceManager.GetString("AddProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შეფასება.
        /// </summary>
        public static string AssessmentDetails {
            get {
                return ResourceManager.GetString("AssessmentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შეფასებები.
        /// </summary>
        public static string AssessmentList {
            get {
                return ResourceManager.GetString("AssessmentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პროექტის წაშლა.
        /// </summary>
        public static string DeleteProject {
            get {
                return ResourceManager.GetString("DeleteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პროექტის რედაქტირება.
        /// </summary>
        public static string EditProject {
            get {
                return ResourceManager.GetString("EditProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შეავსეთ შესაძლებლობები.
        /// </summary>
        public static string FillPossibilities {
            get {
                return ResourceManager.GetString("FillPossibilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შეავსეთ ალბათობები.
        /// </summary>
        public static string FillProbabilities {
            get {
                return ResourceManager.GetString("FillProbabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შეავსეთ რეიტინგები.
        /// </summary>
        public static string FillRatings {
            get {
                return ResourceManager.GetString("FillRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პირდაპირი შეფასება.
        /// </summary>
        public static string ManualAssessment {
            get {
                return ResourceManager.GetString("ManualAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პროექტის დეტალები.
        /// </summary>
        public static string ProjectDetails {
            get {
                return ResourceManager.GetString("ProjectDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პროექტების სია.
        /// </summary>
        public static string ProjectList {
            get {
                return ResourceManager.GetString("ProjectList", resourceCulture);
            }
        }
    }
}
